### ISSUE TITLE
Scoping bug when combining local with function assignment

### ISSUE THREAD

**Issue by Vladinator** [EmmyLua/VSCode-EmmyLua#65]
![image](https://user-images.githubusercontent.com/8304135/90387743-01957400-e087-11ea-9d31-1496c12c5b4f.png)

I suspect it is because I define a function using a local variable that should be then considered local function but it ends up placed in the global scope.

**Comment by winterwolf** [comment]
This is not a bug because this file can be required as module from anywhere. In this case Test3 will not be a global.

**Comment by winterwolf** [comment]
Very interesting. Test4 was defined as local, then it temporary becomes global, because you define a new global function with the same name and it overwrite local variable, so at the end it is local again, but emmylua "remember" that it was global.

![peek](https://user-images.githubusercontent.com/42620439/93147705-a2189b80-f6fa-11ea-868f-bc414a0540d6.gif)

Technically you're right, it's a bug, but you use a very weird way to define this function. You should use

```lua
local function Test4() end
```
instead of
```lua
local Test4
function Test4() end
```

**Comment by Vladinator89** [comment]
Thanks for taking time to look into this ticket.

The origin for this was purely accidental. Sometimes I use(d) this technique to scope variables out of the rest of the code like:

    local MyFunc do
        local internalReusableVariables
        local internalFuncs() end
        function MyFunc(i) end
    end

Purely to have MyFunc exposes as a local to the file scope but have the other internal variables and functions in their own scope to limit autocomplete madness if the file got some size and a lot of these were supposed to not be used elsewhere outside that particular function anyway.
